- src/config/images.js
- src/pages/react-redux-graphql-bootcamp.js
> new quote from Davian Robinson on the bootcamp landing page

- src/components/layout/AcceptCookies.js
- src/layouts/index.js
- src/pages/curriculum.js
- yarn.lock
Adds the accept cookies message.
> adds AcceptCookies.js

- src/components/layout/AcceptCookies.js
- src/components/layout/CallToActionNextTrainings.js
- src/components/layout/Header.js
- src/components/navigation/Breadcrumb.js
- src/components/navigation/menu/index.js
- src/config/styles.js
- add `z-index` values as params
- use the values throughout the code
> add z-index params to code

- src/components/training/UpcomingTrainingSection.js
- src/pages/about-us.js
Currently, this functionality is individual pieces of coding but I will create a 'newsletter-promo' component as part of the next phase which will then be refactored into these pages and also added to course instance pages :)
> newsletter sections added to HP, landing pages and about-us

- src/pages/blog/introduction-to-thinking-in-react.md
- src/pages/blog/learn-react-the-fast-way.md
- src/pages/blog/react-forms-controlled-and-uncontrolled-components.md
- src/pages/blog/react-is-all-about-composition-react-hooks-render-props-hocs.md
- src/pages/blog/secure-react-apps-using-JWT-and-react-router.md
- src/pages/blog/unit-testing-fundamentals-explained-using-javascript.md
This PR adds linking between posts to improve SEO and user navigation
> Linking posts

- src/pages/about-us.js
updated personal info in about-us.js
> updating eva's profile

- src/config/data.js
- src/pages/blog/must-know-javascript-for-react-developers.md
This is the ES6 for react developers blog post 😎
This commit also includes a commented out upcoming bootcamp in data.js which will go live once the venue confirms.
> ES6 blog post

- src/components/layout/Header.js
> fixes styled InfoBox

- src/pages/react-redux-training-amsterdam.js
- src/pages/react-redux-training-barcelona.js
- src/pages/react-redux-training-london.js
As discussed with Paul it removes all the pay by installments
> removes InstallmentsCard

- functions/index.js
- src/api/index.js
- src/components/elements/Card.js
- src/components/form/CheckboxField.js
- src/components/form/Contact.js
- src/components/form/FieldInput.js
- src/components/form/Input.js
- src/components/form/InputField.js
- src/components/form/index.js
- src/components/navigation/menu/Menu.json
- src/components/navigation/menu/PhoneMenu.test.js
- src/components/navigation/menu/__snapshots__/DesktopMenu.test.js.snap
- src/components/navigation/menu/__snapshots__/PhoneMenu.test.js.snap
- src/components/payment/checkout/CheckoutForm.js
- src/components/text/Label.js
- src/components/training/withUpcomingTrainings.js
- src/layouts/reset.css
- src/pages/community.js
- src/pages/interest-form.js
- src/pages/react-workshops.js
- src/pages/thanks-for-signing-up-for-sessions.js
- src/pages/unsubscribe.js
This PR is to add the one day sessions waiting list to the site and a new form to handle that. There is still some small work to be done on styling this (the form checkboxes) and a bit of refactor and tidy up, but I'd like to get it live asap so people can get on the wait list. The important thing to review asap is the text as it was written very fast.
> 1-day Sessions

- src/components/curriculum/CurriculumOneDayStyling.js
- src/components/curriculum/index.js
- src/components/layout/Header.js
- src/components/payment/checkout/CheckoutForm.js
- src/components/training/UpcomingTrainings.js
- src/config/data.js
- src/pages/react-one-day-workshop.js
- src/pages/react-styling-design-system-workshop.js
- src/pages/react-workshops.js
This PR adds an instance page for the Styling in React and Design Systems session.
> One day workshops 

- src/components/layout.js
- src/components/navigation/menu/PhoneMenu/ToggleButton.js
- src/pages/community/meetups/1.js
This PR addresses the 3 new errors that had appeared in the console in dev since Sunday
> Fix console errors

- src/components/layout/Header.js
- src/components/training/UpcomingTrainings.js
- src/config/images.js
- src/pages/community/meetups/1.js
This PR handles the images in the info box.
> Image update

- src/components/layout/Header.js
- src/components/training/UpcomingTrainingSection.js
- src/components/training/UpcomingTrainings.js
- src/config/images.js
- src/pages/community/index.js
- src/pages/community/meetups/1.js
- src/pages/community/meetups/index.js
This PR is a quick fix to solve the problem of duplicate content on the meetups page. Here we create a simple list of meetups using available data, this needs to be re-worked as soon as possible though to have a nicer design as we had previously with our list of upcoming meetups.
> Meetups page

- package.json
- src/components/layout/AcceptCookies.js
- src/components/navigation/Breadcrumb.js
- src/components/navigation/menu/PhoneMenu/ToggleButton.js
- src/components/utils/store.js
- yarn.lock
Reduces the JS that the browser needs to download, parse and execute.
> removes store dependency

- src/components/navigation/menu/DesktopMenu/__snapshots__/DesktopMenu.test.js.snap
- src/components/navigation/menu/Menu.json
- src/components/navigation/menu/PhoneMenu/__snapshots__/PhoneMenu.test.js.snap
- src/pages/community/meetups/index.js
- Updates meetups page header description
- Moves community in main nav under about us
> updates main nav and moves community under about us

- package.json
- yarn.lock
This PR fixes the following error:
> upgrades react-live

- src/components/payment/Payment.test.js
- src/components/payment/checkout/CheckoutContainer.js
- src/components/payment/checkout/Pay.graphql
HEADS UP! We need to merge the UM API before merging this PR
> adds support to buy other event types like meetups

- src/components/training/TrainingCard.js
This contains the changes made by me, @shakersinthedark and @ric9176 in this branch https://github.com/reactgraphqlacademy/reactgraphqlacademy/tree/design-system, used to practice the design system spacing but never got merged.
> adds spacing to TrainingCard.js using the desing system

- src/components/elements/Card.js
- src/components/layout/Footer.js
- src/components/text/index.js
Fixes the following font color issue
> refactores the fontColor function in Card and uses it in Footer too

- src/components/layout/Header.js
- src/config/styles.js
- src/pages/about-us.js
- src/templates/coach.js
- Updates coach profile and adds link to coach profile on the image in the coach list
- Fixes Z_INDEX_TOP on the top nav which overlaps with the home page tabs
- Removes shadow on header border
> updates coaches

- src/components/curriculum/CurriculumPartTime.js
- src/components/curriculum/__snapshots__/CurriculumPartTime.test.js.snap
- src/components/curriculum/sessions/HoCsRenderPropsStateReducerSession.js
- src/pages/react/curriculum.js
Replaces Advanced Redux with Hooks in part-time course
> adds hooks to part-time course
